#=======================================================================================================================
         project(common_module VERSION 0.0.2 LANGUAGES CXX)
#=======================================================================================================================
     add_library(common_module INTERFACE)
#=======================================================================================================================
add_subdirectory(core)
#=======================================================================================================================
add_subdirectory(math)
#=======================================================================================================================