#=======================================================================================================================
         project(common-module LANGUAGES CXX)
#=======================================================================================================================
     add_library(common-module)
#=======================================================================================================================
add_subdirectory(core)
#=======================================================================================================================
add_subdirectory(math)
#=======================================================================================================================