#=======================================================================================================================
         project(common_module LANGUAGES CXX)
#=======================================================================================================================
     add_library(common_module INTERFACE)
#=======================================================================================================================
add_subdirectory(core)
#=======================================================================================================================
add_subdirectory(math)
#=======================================================================================================================